# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a3d121158e7dab65681e93db3792357420d06ea8ccdd6087d8ab58fdced1ed231264e4672a20f22b52524d80eac3819ac4909c6ea477c755d1f33520dacb4ca

test:
  secret_key_base: 9b0eaaf5385247abe203d435b39c7be15d482355258dc285a75a892b9240b723552b178a9f482804c5ad277627d97cc0ebfd849270b94e98b9f1e74caee17c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
